// Generated by gencpp from file iris/angka.msg
// DO NOT EDIT!


#ifndef IRIS_MESSAGE_ANGKA_H
#define IRIS_MESSAGE_ANGKA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iris
{
template <class ContainerAllocator>
struct angka_
{
  typedef angka_<ContainerAllocator> Type;

  angka_()
    : number(0)  {
    }
  angka_(const ContainerAllocator& _alloc)
    : number(0)  {
  (void)_alloc;
    }



   typedef uint8_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::iris::angka_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iris::angka_<ContainerAllocator> const> ConstPtr;

}; // struct angka_

typedef ::iris::angka_<std::allocator<void> > angka;

typedef boost::shared_ptr< ::iris::angka > angkaPtr;
typedef boost::shared_ptr< ::iris::angka const> angkaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iris::angka_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iris::angka_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iris::angka_<ContainerAllocator1> & lhs, const ::iris::angka_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iris::angka_<ContainerAllocator1> & lhs, const ::iris::angka_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iris

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iris::angka_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iris::angka_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iris::angka_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iris::angka_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iris::angka_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iris::angka_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iris::angka_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29e94f7568510a2f9241abcc8f191b4f";
  }

  static const char* value(const ::iris::angka_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29e94f7568510a2fULL;
  static const uint64_t static_value2 = 0x9241abcc8f191b4fULL;
};

template<class ContainerAllocator>
struct DataType< ::iris::angka_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iris/angka";
  }

  static const char* value(const ::iris::angka_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iris::angka_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 number\n"
;
  }

  static const char* value(const ::iris::angka_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iris::angka_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct angka_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iris::angka_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iris::angka_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRIS_MESSAGE_ANGKA_H
